services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    image: frontend

  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "80:80"
    image: web
    depends_on:
      - frontend
      