name: vertile

networks:
  internal_network:
    driver: bridge
services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: main
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal_network

  app:
    build:
      context: ./app
    container_name: vertile-app
    image: app
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app

  trainer:
    build:
      context: ./trainer
    container_name: trainer
    volumes:
      - type: bind
        source: ./trainer
        target: /trainer
    ports:
      - "8000:8000"
    image: trainer
    networks:
      - internal_network
volumes:
  db-data:
    
